// Coverage gate for the Lumen backend.
//
//   dotnet test backend/Lumen.slnx --settings backend/coverlet.runsettings --collect:"XPlat Code Coverage" --nologo --results-directory TestResults
//   dotnet run backend/tools/check-coverage.cs
//
// A .NET 10 file-based app: no project, no new NuGet package, `dotnet run` is the whole toolchain.
// Reads every coverage.cobertura.xml under the results directory, merges them, and reports TWO
// figures against ONE denominator split by path:
//
//   * whole tree     — every instrumented line under backend/src
//   * hand-written   — the same, minus generated EF migrations and LumenDbContextModelSnapshot.cs
//
// The gate is the hand-written figure (plan G15). BOTH are always printed, because the whole point of
// G15 is that nobody should later read "97%" as whole-tree coverage.
//
// WHY THIS FILE EXISTS AT ALL, rather than coverlet's ExcludeByFile:
//
//   1. ExcludeByFile is a glob. The client's gate was written with a glob first and it was WRONG: `*`
//      did not cross `/` the way the author assumed, nested generated files stayed in the denominator,
//      and the gate reported 58.6% against a true 97.60% until a review caught it. So the exclusion
//      here is an ordinal PATH match on a normalized path, with a leading separator forced on, and it
//      is exercised by the fixtures in `--self-test`.
//   2. Excluding at collection time cannot report both figures — the excluded lines are simply gone
//      from the report. Partitioning after the fact reports both from one run.
//
// WHAT IS EXCLUDED, and why it is exactly this:
//
//   backend/src/**/Migrations/**            EF-generated: Up/Down, the per-migration .Designer.cs
//   backend/src/**/LumenDbContextModelSnapshot.cs   snapshot regenerated by `dotnet ef`
//
// Neither is executed by any test — LiveStack applies migrations out of process via `dotnet ef` — so
// they report zero hits forever, and at T20 they are 4,340 of 8,347 instrumented lines (52%). Nothing
// else is excluded. In particular the source-generated RegexGenerator output under obj/ is LEFT IN
// even though it is machine-written, because dropping it would RAISE the reported figure and the one
// thing a coverage gate must never do is move its own denominator to reach its own threshold.
//
// Usage:
//   dotnet run backend/tools/check-coverage.cs [-- <results-dir>] [--threshold <pct>] [--self-test]

using System.Globalization;
using System.Xml.Linq;

const double DefaultThreshold = 70.0;

var resultsDirectory = "TestResults";
var threshold = DefaultThreshold;

for (var i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--self-test":
            return SelfTest();
        case "--threshold" when i + 1 < args.Length:
            threshold = double.Parse(args[++i], CultureInfo.InvariantCulture);
            break;
        default:
            resultsDirectory = args[i];
            break;
    }
}

return Gate(resultsDirectory, threshold, quiet: false);

// ---------------------------------------------------------------------------------------------

/// <summary>
/// A source file is GENERATED if its path contains a `Migrations` directory at any depth, or the file
/// is the EF model snapshot.
///
/// Matched on a normalized path with a separator forced onto the front, so the directory is recognised
/// wherever it sits — `a/b/Migrations/x.cs`, a report rooted at `Migrations/x.cs`, or a Windows report
/// spelling it `a\b\Migrations\x.cs`. That last one is not hypothetical: coverlet emits the host's
/// separator, so the same report is backslashed on a dev machine and forward-slashed in CI, and a
/// checker that matched one of them would silently under-exclude on the other — the exact failure the
/// client's glob had.
///
/// The `/Migrations/` form (separators on BOTH sides) is deliberate: it will not match a file merely
/// NAMED Migrations.cs, nor a directory called `MigrationsHelpers`.
/// </summary>
static bool IsGenerated(string sourceFile)
{
    var path = "/" + sourceFile.Replace('\\', '/').TrimStart('/');
    return path.Contains("/Migrations/", StringComparison.Ordinal)
           || path.EndsWith("/LumenDbContextModelSnapshot.cs", StringComparison.Ordinal);
}

/// <summary>
/// Merges every cobertura report in <paramref name="directory"/> into one line map. Reports overlap by
/// design (three suites, one product tree), and a line covered by ANY suite is covered — so hits are
/// merged with max, not summed and not last-wins. Summing would be harmless here, but last-wins would
/// silently drop unit-test coverage of a file the integration suite also touched.
/// </summary>
static Dictionary<string, Dictionary<int, int>> ReadReports(string directory)
{
    var lines = new Dictionary<string, Dictionary<int, int>>(StringComparer.Ordinal);

    foreach (var report in Directory.EnumerateFiles(directory, "coverage.cobertura.xml", SearchOption.AllDirectories))
    {
        foreach (var @class in XDocument.Load(report).Descendants("class"))
        {
            var file = (string?)@class.Attribute("filename");
            if (file is null) continue;

            var normalized = file.Replace('\\', '/');
            if (!lines.TryGetValue(normalized, out var byLine))
                lines[normalized] = byLine = new Dictionary<int, int>();

            foreach (var line in @class.Descendants("line"))
            {
                if (!int.TryParse((string?)line.Attribute("number"), out var number)) continue;
                if (!int.TryParse((string?)line.Attribute("hits"), out var hits)) continue;

                byLine[number] = byLine.TryGetValue(number, out var existing) ? Math.Max(existing, hits) : hits;
            }
        }
    }

    return lines;
}

static int Gate(string directory, double threshold, bool quiet)
{
    if (!Directory.Exists(directory))
    {
        Console.Error.WriteLine($"'{directory}' not found — run the coverage command above first.");
        return 2;
    }

    var lines = ReadReports(directory);
    if (lines.Count == 0)
    {
        Console.Error.WriteLine($"no coverage.cobertura.xml under '{directory}' — run the coverage command above first.");
        return 2;
    }

    long total = 0, covered = 0, generatedTotal = 0, generatedCovered = 0;
    var generatedFiles = 0;

    foreach (var (file, byLine) in lines)
    {
        long fileTotal = byLine.Count;
        long fileCovered = byLine.Values.Count(hits => hits > 0);

        total += fileTotal;
        covered += fileCovered;

        if (!IsGenerated(file)) continue;

        generatedFiles++;
        generatedTotal += fileTotal;
        generatedCovered += fileCovered;
    }

    var handTotal = total - generatedTotal;
    var handCovered = covered - generatedCovered;

    if (handTotal == 0)
    {
        Console.Error.WriteLine("every instrumented line was excluded — the exclusion is wrong, not the code.");
        return 2;
    }

    var wholeTree = 100.0 * covered / total;
    var handWritten = 100.0 * handCovered / handTotal;
    var generatedShare = 100.0 * generatedTotal / total;

    if (!quiet)
    {
        Console.WriteLine($"whole tree            {covered,6}/{total,-6} = {wholeTree,6:F2}%   (backend/src, everything instrumented)");
        Console.WriteLine($"  generated           {generatedCovered,6}/{generatedTotal,-6} = {(generatedTotal == 0 ? 0 : 100.0 * generatedCovered / generatedTotal),6:F2}%   ({generatedFiles} files, {generatedShare:F1}% of all instrumented lines)");
        Console.WriteLine($"  hand-written  GATED {handCovered,6}/{handTotal,-6} = {handWritten,6:F2}%   (excludes **/Migrations/** and LumenDbContextModelSnapshot.cs)");
        Console.WriteLine();
    }

    if (handWritten < threshold)
    {
        Console.Error.WriteLine(
            $"GATE FAIL: hand-written coverage {handWritten:F2}% < {threshold:F0}% threshold. " +
            $"Do NOT widen the exclusion list — extend the tests.");
        return 1;
    }

    Console.WriteLine($"GATE PASS: hand-written coverage {handWritten:F2}% >= {threshold:F0}%.");
    return 0;
}

/// <summary>
/// Proves the two things this file can get wrong, on synthetic reports written to a temp directory:
/// that the path match excludes generated code at ANY depth and under EITHER separator (an
/// under-excluding matcher was the client's bug), and that the gate actually FAILS below the
/// threshold rather than passing quietly.
/// </summary>
static int SelfTest()
{
    var failures = 0;

    void Check(string what, bool ok)
    {
        Console.WriteLine($"  [{(ok ? "PASS" : "FAIL")}] {what}");
        if (!ok) failures++;
    }

    Console.WriteLine("path matcher:");
    Check("nested migration (forward slashes)", IsGenerated("Lumen.Infrastructure/Persistence/Migrations/20260601_X.cs"));
    Check("nested migration (backslashes)", IsGenerated(@"Lumen.Infrastructure\Persistence\Migrations\20260601_X.cs"));
    Check("deeply nested migration", IsGenerated("a/b/c/d/e/Migrations/f/g/X.Designer.cs"));
    Check("report rooted at Migrations/", IsGenerated("Migrations/X.cs"));
    Check("absolute path", IsGenerated("/repo/backend/src/Lumen.Infrastructure/Persistence/Migrations/X.cs"));
    Check("model snapshot", IsGenerated("Lumen.Infrastructure/Persistence/Migrations/LumenDbContextModelSnapshot.cs"));
    Check("model snapshot outside Migrations/", IsGenerated("Lumen.Infrastructure/LumenDbContextModelSnapshot.cs"));
    Check("hand-written service is NOT excluded", !IsGenerated("Lumen.Api/Symptoms/SymptomService.cs"));
    Check("a file merely NAMED Migrations.cs is NOT excluded", !IsGenerated("Lumen.Api/Migrations.cs"));
    Check("MigrationsHelpers/ is NOT excluded", !IsGenerated("Lumen.Api/MigrationsHelpers/X.cs"));

    var root = Path.Combine(Path.GetTempPath(), "lumen-coverage-selftest-" + Guid.NewGuid().ToString("N"));
    try
    {
        // A tree whose HAND-WRITTEN half is 1/4 = 25% while the whole tree reads 91% — because the
        // generated half is (impossibly) fully covered. Any checker that failed to exclude the
        // generated file would report a comfortable pass on a codebase with 25% real coverage.
        WriteReport(Path.Combine(root, "unit"), [
            ("Lumen.Api/Symptoms/SymptomService.cs", [(1, 1), (2, 0), (3, 0), (4, 0)]),
            (@"Lumen.Infrastructure\Persistence\Migrations\20260601_X.cs", Enumerable.Range(1, 40).Select(n => (n, 1)).ToArray()),
        ]);

        Console.WriteLine();
        Console.WriteLine("gate below threshold (expect exit 1):");
        var exit = Gate(root, DefaultThreshold, quiet: false);
        Check("gate returns 1", exit == 1);

        Console.WriteLine("gate above a threshold the hand-written figure clears (expect exit 0):");
        Check("gate returns 0 at 20%", Gate(root, 20.0, quiet: false) == 0);

        Console.WriteLine("empty results directory (expect exit 2):");
        Check("gate returns 2", Gate(Path.Combine(root, "nothing-here"), DefaultThreshold, quiet: true) == 2);
    }
    finally
    {
        if (Directory.Exists(root)) Directory.Delete(root, recursive: true);
    }

    Console.WriteLine();
    Console.WriteLine(failures == 0 ? "SELF-TEST PASS" : $"SELF-TEST FAIL ({failures})");
    return failures == 0 ? 0 : 1;
}

static void WriteReport(string directory, (string File, (int Line, int Hits)[] Lines)[] files)
{
    Directory.CreateDirectory(directory);

    var classes = files.Select(f => new XElement(
        "class",
        new XAttribute("filename", f.File),
        new XElement("lines", f.Lines.Select(l =>
            new XElement("line", new XAttribute("number", l.Line), new XAttribute("hits", l.Hits))))));

    new XDocument(new XElement("coverage", new XElement("packages", new XElement("package", new XElement("classes", classes)))))
        .Save(Path.Combine(directory, "coverage.cobertura.xml"));
}
