// <auto-generated />
using System;
using System.Collections.Generic;
using Lumen.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumen.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LumenDbContext))]
    [Migration("20260807002830_AddCycleSettingsPauseSpansAndPreferences")]
    partial class AddCycleSettingsPauseSpansAndPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumen.Domain.Entities.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("EntityId", "Action");

                    b.ToTable("admin_audit_log", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConsentedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.CycleDayLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Energy")
                        .HasColumnType("smallint");

                    b.Property<short?>("Libido")
                        .HasColumnType("smallint");

                    b.Property<short?>("Mood")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("NotesEnc")
                        .HasColumnType("bytea");

                    b.Property<short?>("Pain")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Day")
                        .IsUnique();

                    b.ToTable("cycle_day_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_cycle_day_logs_mood_range", "\"Mood\" >= 1 AND \"Mood\" <= 4");

                            t.HasCheckConstraint("ck_cycle_day_logs_pain_range", "\"Pain\" >= 0 AND \"Pain\" <= 10");
                        });
                });

            modelBuilder.Entity("Lumen.Domain.Entities.CycleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("FlowIntensity")
                        .HasColumnType("smallint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<byte[]>("NotesEnc")
                        .HasColumnType("bytea");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredOn");

                    b.HasIndex("UserId", "Kind", "OccurredOn")
                        .IsUnique();

                    b.ToTable("cycle_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_cycle_events_flow_intensity_range", "\"FlowIntensity\" >= 1 AND \"FlowIntensity\" <= 4");
                        });
                });

            modelBuilder.Entity("Lumen.Domain.Entities.CyclePhaseOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Boundary")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("CycleStartOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CycleStartOn");

                    b.HasIndex("UserId", "CycleStartOn", "Phase", "Boundary")
                        .IsUnique();

                    b.ToTable("cycle_phase_overrides", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.CycleTrackingPauseSpan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"EndedOn\" IS NULL");

                    b.HasIndex("UserId", "StartedOn");

                    b.ToTable("cycle_tracking_pause_spans", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.Symptom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Intensity")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("NotesEnc")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.PrimitiveCollection<List<string>>("PainTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Region")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("unspecified");

                    b.Property<string>("Side")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("SymptomCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<List<string>>("Triggers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredOn", "OccurredAt");

                    b.ToTable("symptoms", null, t =>
                        {
                            t.HasCheckConstraint("ck_symptoms_intensity_range", "\"Intensity\" >= 0 AND \"Intensity\" <= 10");
                        });
                });

            modelBuilder.Entity("Lumen.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<DateTimeOffset?>("OnboardingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailHash")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserCycleSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoDetectPeriodStartEnabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<short>("AvgCycleLengthDays")
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)28);

                    b.Property<short?>("AvgPeriodLengthDays")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PauseReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("PausedSince")
                        .HasColumnType("date");

                    b.Property<bool>("PhasePredictionEnabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Regularity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("somewhat");

                    b.Property<bool>("ShowFertilityWindowEnabled")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("TrackingPaused")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("user_cycle_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_cycle_settings_avg_cycle_length_positive", "\"AvgCycleLengthDays\" > 0");

                            t.HasCheckConstraint("ck_user_cycle_settings_avg_period_length_positive", "\"AvgPeriodLengthDays\" IS NULL OR \"AvgPeriodLengthDays\" > 0");
                        });
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PushToken")
                        .IsUnique();

                    b.ToTable("user_devices", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Selected")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GoalCode")
                        .IsUnique();

                    b.ToTable("user_goals", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserHormonePref", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Charted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HormoneCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "HormoneCode")
                        .IsUnique();

                    b.ToTable("user_hormone_prefs", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserKey", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("VaultKeyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("WrappedDek")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("UserId");

                    b.ToTable("user_keys", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserNotificationPref", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CategoryCode")
                        .IsUnique();

                    b.ToTable("user_notification_prefs", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserProfileEnc", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("BioEnc")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("DisplayNameEnc")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("DobEnc")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("user_profile_enc", (string)null);
                });

            modelBuilder.Entity("Lumen.Domain.Entities.ConsentRecord", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.CycleDayLog", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.CycleEvent", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.CyclePhaseOverride", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.CycleTrackingPauseSpan", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.Symptom", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserCycleSettings", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Lumen.Domain.Entities.UserCycleSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserDevice", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserGoal", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserHormonePref", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserKey", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Lumen.Domain.Entities.UserKey", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserNotificationPref", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Domain.Entities.UserProfileEnc", b =>
                {
                    b.HasOne("Lumen.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Lumen.Domain.Entities.UserProfileEnc", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
